services:
  backend:
    build: ./backend
    container_name: ptcg-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/data/app.db
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8000/api
    container_name: ptcg-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
